# Generated by Django 2.2.2 on 2019-06-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('bug', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Bug')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tuple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
                ('triple', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Tuple')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProductType')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.PackageType')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1000)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.LocationType'),
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.EnvironmentType'),
        ),
        migrations.AddField(
            model_name='environment',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Location'),
        ),
        migrations.AddField(
            model_name='environment',
            name='package',
            field=models.ManyToManyField(to='core.Package'),
        ),
        migrations.AddField(
            model_name='environment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product'),
        ),
        migrations.AddField(
            model_name='environment',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Source'),
        ),
        migrations.CreateModel(
            name='BugProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.CharField(max_length=100, unique=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bug')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BugStatusType')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='product',
            field=models.ManyToManyField(through='core.BugProductStatus', to='core.Product'),
        ),
        migrations.AddField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
