# Generated by Django 2.2.2 on 2019-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
