FROM python:2.7-slim

ADD . ./myapp

WORKDIR ./myapp

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc python-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r requirements.txt \
    && apt-get purge -y --auto-remove gcc python-dev

CMD python main.py

