FROM python:2.7-slim

ADD . /myapp
ADD repo-key /

WORKDIR /myapp

RUN apt-get update \
    && apt-get install -y --no-install-recommends git gcc ssh python-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r requirements.txt \
    && apt-get purge -y --auto-remove gcc python-dev

RUN chmod 600 /repo-key \
    && echo "IdentityFile /repo-key" >> /etc/ssh/ssh_config \
    && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config


#CMD python consumer_leap.py

